### ISSUE TITLE
[feat] support multiple rules with separator in config

### ISSUE THREAD

**Issue by Triple-Z** [gaocegege/double-entry-generator#10]
If the rules have the same `targetAccount`, we should write rules like the following:

```yaml
- peer: 云膳过桥米线
  targetAccount: Expenses:Food:Meal
- peer: 餐厅
  targetAccount: Expenses:Food:Meal
```

In order to reduce writing nonsense configs, the WeChat provider should support multiple rules at the same time.

An ideal config is like the following, it should be equal to the above rules:

```yaml
- peer: 云膳过桥米线,餐厅
  targetAccount: Expenses:Food:Meal
```

In fact, we implicit the separator as a comma character `,`. Users also can specify the separator manually:

```yaml
- peer: 云膳过桥米线?餐厅
  separator: ?
  targetAccount: Expenses:Food:Meal
```

**Comment by Triple-Z** [comment]
Maybe the `alipay` provider has the same requirement?
/cc @gaocegege

**Comment by Triple-Z** [comment]
The fields(peer, item, type) inside each rule are `AND` relation, but keywords inside each field are `OR` relation.

```yaml
- peer: 云膳过桥米线,餐厅
  item: 盖浇饭,米线
  targetAccount: Expenses:Food:Meal
```

The rules are:
- `peer:云膳过桥米线` **AND** `item:盖浇饭`
- `peer:餐厅` **AND** `item:盖浇饭`
- `peer:云膳过桥米线` **AND** `item:米线`
- `peer:餐厅` **AND** `item:米线`

Or the other way:
```
(peer:云膳过桥米线 OR peer:餐厅) AND (item:盖浇饭 OR item:米线)
```
