### ISSUE TITLE
[feat] support matching accounts via all rules

### ISSUE THREAD

**Issue by Triple-Z** [gaocegege/double-entry-generator#4]
AFAIK, with WeChat bills, using `peer` can generally decide the `plusAccount`(usually Expanse accounts) and using `method` can decide the `minusAccount`(usually Asset accounts) .

So I suggest that `wechat` provider should support a config format like this to find the proper `plusAccount` and `minusAccount`:
```yaml
- method: 零钱
      minusAccount: Assets:Digital:Wechat:Cash
- peer: 地铁
      plusAccount: Expenses:Transport:Metro
- peer: 滴滴
      plusAccount: Expenses:Transport:Taxi
```

An example bill:

```
peer: 广州地铁
method: 零钱通
```

and you can get:

```
plusAccount: Expenses:Transport:Metro
minusAccount: Assets:Digital:Wechat:Cash
```
